Repository kubernetes-sigs/aws-fsx-openzfs-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#16 Add workflows to publish images to ECR public repo
  .dockerignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/container-image.yaml
  .github/workflows/release.yaml
  CHANGELOG-0.x.md
Labels: size/L, lgtm, cncf-cla: yes, approved

#15 Add Dynamic Object Creation Using Json
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_fsx.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/sanity/sanity_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#17 Update repo to support beta release v0.1.0
  .github/cr.yaml
  .github/workflows/container-image.yaml
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
  CHANGELOG-0.x.md
  CHANGELOG.md
  README.md
  RELEASE.md
  charts/aws-fsx-openzfs-csi-driver/CHANGELOG.md
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/install.md
  hack/release
  overlays/dev/kustomization.yaml
Labels: size/L, lgtm, cncf-cla: yes, approved

#20 Add check for Provenance
  Makefile
  hack/provenance
Labels: size/M, lgtm, cncf-cla: yes, approved

#21 fix helm chart release condition
  .github/workflows/helm-chart-release.yaml
Labels: size/XS, lgtm, cncf-cla: yes, approved

#23 Release helm chart v0.1.0
  charts/aws-fsx-openzfs-csi-driver/Chart.yaml
Labels: size/XS, lgtm, cncf-cla: yes, approved

#26 Fix docs for JSON refactor
  docs/FAQ.md
  docs/install.md
  docs/parameters.md
  docs/tagging.md
  pkg/driver/controller_test.go
  pkg/driver/mocks/mock_cloud.go
Labels: size/L, lgtm, cncf-cla: yes, approved

#32 Fix Snapshot Parameters Bug
  pkg/driver/controller.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#33 Fix Update In Progress Failure During ResizeFileSystem
  pkg/cloud/cloud.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#31 Fix Sanity Tests
  docs/FAQ.md
  docs/parameters.md
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/fakes.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/identity.go
  pkg/driver/node.go
  tests/sanity/sanity_test.go
Labels: size/L, lgtm, cncf-cla: yes, approved

#30 Modularize the controller and node services
  charts/aws-fsx-openzfs-csi-driver/templates/controller-deployment.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/node-daemonset.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  cmd/cmd.go
  cmd/main.go
  cmd/options.go
  cmd/options/controller_options.go
  cmd/options/controller_options_test.go
  cmd/options/node_options.go
  cmd/options/node_options_test.go
  cmd/options/server_options.go
  cmd/options/server_options_test.go
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  go.mod
  go.sum
  hack/update-gomock
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/cloud/mocks/mock_fsx.go
  pkg/cloud/mocks/mock_metadata.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mount.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/sanity/sanity_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#34 Add Support for Operating Modes and Metadata Collection via the Kubernetes API
  Makefile
  README.md
  charts/aws-fsx-openzfs-csi-driver/templates/clusterrole-csi-node.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/clusterrolebinding-csi-node.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/controller-deployment.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/node-daemonset.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  cmd/main.go
  cmd/options.go
  cmd/options/server_options.go
  deploy/kubernetes/base/clusterrole-csi-node.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/options.md
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/fakes.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_k8s.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/cloud/mocks/mock_metadata.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/node.go
  pkg/driver/version.go
Labels: size/XL, lgtm, cncf-cla: yes, approved

#35 Add support for node startup taints
  charts/aws-fsx-openzfs-csi-driver/templates/clusterrole-csi-node.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/node-daemonset.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  deploy/kubernetes/base/clusterrole-csi-node.yaml
  docs/install.md
  hack/update-gomock
  pkg/driver/constants.go
  pkg/driver/mocks/mock_k8s_client.go
  pkg/driver/mocks/mock_k8s_corev1.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#36 Add inflight checks to node mounting operations
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#39 Minor documentation adjustments
  README.md
  docs/install.md
  docs/options.md
  docs/parameters.md
  docs/tagging.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#38 Adopt Kubernetes standard logging patterns
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/node.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#29 Adopt Kubernetes recommended labels
  charts/aws-fsx-openzfs-csi-driver/templates/_helpers.tpl
  charts/aws-fsx-openzfs-csi-driver/templates/controller-deployment.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/node-daemonset.yaml
  charts/aws-fsx-openzfs-csi-driver/templates/poddisruptionbudget-controller.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/controller-serviceaccount.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/base/node-serviceaccount.yaml
  deploy/kubernetes/base/poddisruptionbudget-controller.yaml
  docs/install.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#41 Release 1.0.0 part 1/3: CHANGELOG, README, Makefile
  CHANGELOG.md
  Makefile
  README.md
  docs/install.md
Labels: needs-ok-to-test, lgtm, cncf-cla: yes, size/S, approved

#42 Release 1.0.0 part 2/3: helm and kustomize
  charts/aws-fsx-openzfs-csi-driver/CHANGELOG.md
  charts/aws-fsx-openzfs-csi-driver/Chart.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
Labels: ok-to-test, lgtm, cncf-cla: yes, size/S, approved

#43 Release 1.0 - part 3/3, merge to main
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-fsx-openzfs-csi-driver/CHANGELOG.md
  charts/aws-fsx-openzfs-csi-driver/Chart.yaml
  charts/aws-fsx-openzfs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  docs/install.md
Labels: ok-to-test, size/M, lgtm, cncf-cla: yes, approved

#44 Remove BETA warnings from README
  README.md
Labels: ok-to-test, size/XS, lgtm, cncf-cla: yes, approved
